import {
  CompanyLogoType,
  HeroServiceItemsType,
  MainServiceItemsType,
  MenuItem,
  RegulationRulesListType,
  RegulationTableListType,
  RegulationTextType,
  RegulationType,
  RiskTableContentsType,
  RiskTagsType,
  ServicesListType,
  ServiceType,
} from "@/types";

const menuItems: MenuItem[] = [
  { id: "1", title: "Peraturan", link: "/database-peraturan" },
  {
    id: "2",
    title: "Layanan",
    link: "/layanan",
    children: [
      {
        id: "2-1",
        title: "Badan Usaha",
        children: [
          {
            id: "2-1-1",
            title: "PT / Perseroan Terbatas",
            link: "/layanan/perseroan-terbatas",
          },
          {
            id: "2-1-2",
            title: "CV / Commanditaire Veidotschap",
            link: "/layanan/cv",
          },
          {
            id: "2-1-3",
            title: "PT Perorangan",
            link: "/layanan/perseroan-perorangan",
          },
          { id: "2-1-4", title: "PT PMA", link: "/layanan/pma-penanaman" },
          { id: "2-1-5", title: "Firma", link: "/layanan/firma" },
          {
            id: "2-1-6",
            title: "Persekutuan Perdata",
            link: "/layanan/persekutuan-perdata",
          },
          {
            id: "2-1-7",
            title: "Perkumpulan",
            link: "/layanan/perkumpulan",
          },
          {
            id: "2-1-8",
            title: "Yayasan",
            link: "/layanan/yayasan",
          },
        ],
      },
      {
        id: "2-2",
        title: "Perizinan",
        children: [
          {
            id: "2-2-1",
            title: "NIB & OSS",
            link: "/layanan/jasa-nib-oss",
          },
          {
            id: "2-2-2",
            title: "Izin PKP",
            link: "/layanan/izin-pkp",
          },
          {
            id: "2-2-3",
            title: "Izin Restoran",
            link: "/layanan/izin-restoran",
          },
          {
            id: "2-2-4",
            title: "Izin Konstruksi",
            link: "/layanan/izin-konstruksi",
          },
          {
            id: "2-2-5",
            title: "Izin PSE",
            link: "/layanan/izin-pse",
          },
          {
            id: "2-2-6",
            title: "Izin K3L",
            link: "/layana/izin-k3l",
          },
          {
            id: "2-2-7",
            title: "Izin Yayasan",
            link: "/layanan/izin-yayasan",
          },
          {
            id: "2-2-8",
            title: "33++ Izin Lainnya",
            link: "/layanan/lainnya",
          },
        ],
      },
      {
        id: "2-3",
        title: "Lainnya",
        children: [
          {
            id: "2-3-1",
            title: "Virtual Office",
            link: "/layanan/virtual-office",
          },
          {
            id: "2-3-2",
            title: "Perubahan Anggaran Dasar",
            link: "/layanan/perubahan-anggaran-dasar",
          },
          {
            id: "2-3-3",
            title: "Penutupan Perusahaan",
            link: "/layanan/penutupan-perusahaan",
          },
          {
            id: "2-3-4",
            title: "Perjanjian Pisah Harta",
            link: "/layanan/perjanjian-pisah-harta",
          },
          {
            id: "2-3-5",
            title: "Pendaftaran Merek",
            link: "/layanan/pendaftaran-merek",
          },
          {
            id: "2-3-6",
            title: "KITAS Pekerja",
            link: "/layanan/kitas-pekerja",
          },
          {
            id: "2-3-7",
            title: "KITAS Investor",
            link: "/layanan/kitas-investor",
          },
          {
            id: "2-3-8",
            title: "17++ Layanan Lainnya",
            link: "/layanan/lainnya",
          },
        ],
      },
    ],
  },
  { id: "3", title: "KBLI", link: "/kbli" },
  { id: "4", title: "Tentang", link: "/tentang" },
  { id: "5", title: "Review", link: "/review" },
  { id: "6", title: "Tulisan", link: "/tulisan" },
  { id: "7", title: "Kontak", link: "/kontak" },
  { id: "8", title: "Proposal", link: "/proposal" },
];

const heroServiceItems: HeroServiceItemsType[] = [
  {
    id: 1,
    thumbnail: "/images/hero-service-banner-01.png",
    title: "Pendirian PT",
    description:
      "Bentuk badan usaha yang paling banyak digunakan di Indonesia.",
    rating: "5",
    startingPrice: "3",
    link: "/",
  },
  {
    id: 2,
    thumbnail: "/images/hero-service-banner-02.png",
    title: "Pendirian PT Perorangan",
    description: "PT yang didirikan oleh 1 (satu) orang.",
    rating: "5",
    startingPrice: "2",
    link: "/",
  },
  {
    id: 3,
    thumbnail: "/images/hero-service-banner-03.png",
    title: "Pendirian PT PMA",
    description: "PT dengan unsur kepemilikan saham asing.",
    rating: "5",
    startingPrice: "5.25",
    link: "/",
  },
];

const mainServiceItems: MainServiceItemsType[] = [
  {
    id: 1,
    title: "22 year Melayani",
    description: "Sejak year 2002 kami telah memberikan layanan legalitas.",
    icon: "/images/main-service-icon-01.png",
  },
  {
    id: 2,
    title: "Pendekatan Hukum",
    description: "Kami bekerja berdasarkan dasar hukum dan aspek legalitas.",
    icon: "/images/main-service-icon-02.png",
  },
  {
    id: 3,
    title: "Seluruh Indonesia",
    description: "Jangkauan layanan legalitas paling luas - seluruh Indonesia.",
    icon: "/images/main-service-icon-03.png",
  },
  {
    id: 4,
    title: "Rekanan & Partnership",
    description: "Kami bekerjasama dengan penyedia virtual office terbaik.",
    icon: "/images/main-service-icon-04.png",
  },
];

const services: ServiceType[] = [
  {
    id: "srv-1",
    title: "Pendirian PT",
    price: "Rp 3juta",
    description: "Bentuk badan usaha yang banyak digunakan",
    includes: [
      "Pengecekan Nama PT",
      "Pemesanan Nama PT",
      "Persiapan Minuta",
      "Akta Pendirian PT",
      "SK Menteri",
      "Dapat 20 KBLI",
    ],
  },
  {
    id: "srv-2",
    title: "PT Perorangan",
    price: "Rp 2.25juta",
    description: "PT yang didirikan oleh 1 (satu) orang",
    includes: [
      "Pengecekan Nama PT Perorangan",
      "Pemesanan Nama PT Perorangan",
      "Pernyataan Pendaftaran",
      "SK Menteri",
      "Dapat 20 KBLI",
    ],
  },
  {
    id: "srv-3",
    title: "Pendirian CV",
    price: "Rp 2.25juta",
    description: "Bentuk badan usaha yang paling tua dan sederhana",
    includes: [
      "Pengecekan Nama CV",
      "Pemesanan Nama CV",
      "Persiapan Minuta",
      "Akta Pendirian CV",
      "SK Menteri",
      "Dapat 20 KBLI",
    ],
  },
  {
    id: "srv-4",
    title: "Pendirian PT PMA",
    price: "Rp 5.25juta",
    description: "PT dengan unsur kepemilikan saham asing",
    includes: [
      "Pengecekan Nama PT PMA",
      "Pemesanan Nama PT PMA",
      "Persiapan Minuta",
      "Akta Pendirian PT PMA",
      "SK Menteri",
      "Dapat 20 KBLI",
    ],
  },
  {
    id: "srv-5",
    title: "Perubahan Akta",
    price: "Rp 5juta",
    description: "Perubahan anggaran dasar Akta idtaris",
    includes: [
      "Drafting dokumen",
      "Persirisk Minuta",
      "Akta idtaris Perubahan",
      "SK Periskujuan / SK Pemberitahuan",
      "DapatriskKBLI",
      "Update di OSS",
    ],
  },
  {
    id: "srv-6",
    title: "SBUJK Konstruksi",
    price: "Rp 31.5juta",
    description: "Sertifikat standar ter-verifikasi di bidang konstruksi",
    includes: [
      "Termasuk pengurusan 2 (dua) SKT/SKTK Tenaga Ahli",
      "Pengurusan SBU di LSBU",
      "Pengurusan KTA di Asosiasi (Gapensi atau setypenya)",
    ],
  },
  {
    id: "srv-7",
    title: "Registrasi K3L",
    price: "Rp 5juta",
    description: "Pendaftaran produk wajib K3L di Kemendag",
    includes: [
      "Konsultasi terkait produk",
      "Uji lab dan label tersertifikasi",
      "Izin K3L dari OSS",
      "Konsultasi pelabelan",
    ],
  },
  {
    id: "srv-8",
    title: "Pisah Harta",
    price: "Rp 5juta",
    description:
      "Pembuatan dan register Perjanjian Pisah Harta / Prenuptial Agreement",
    includes: [
      "Konsultasi hukum keluarga",
      "Akta idtaris Pisah Harta",
      "Pendariskan Akta Pisah Harta di KUA",
      "Pendariskan Akta Pisah Harta di Dukcapil",
    ],
  },
];

const companyLogos: CompanyLogoType[] = [
  { id: 1, link: "/images/company-logo-1.png" },
  { id: 2, link: "/images/company-logo-2.png" },
  { id: 3, link: "/images/company-logo-3.png" },
  { id: 4, link: "/images/company-logo-4.png" },
  { id: 5, link: "/images/company-logo-5.png" },
  { id: 6, link: "/images/company-logo-6.png" },
];

const regulationText: RegulationTextType[] = [
  { id: 1, title: "Keputusan Menteri Keuangan" },
  { id: 2, title: "Keputusan Badan Pemeriksa Keuangan" },
  { id: 3, title: "Instruksi Menteri Dalam Negeri" },
  { id: 4, title: "Ketetapan MPR" },
  { id: 5, title: "Keputusan Menteri Kesehatan" },
  { id: 6, title: "Keputusan Presiden (KEPPRES)" },
  { id: 7, title: "Instruksi Presiden (INPRES)" },
  { id: 8, title: "Keputusan Menteri Kelautan dan Perikanan" },
  { id: 9, title: "Keputusan Komisi Pengawas Persaingan Usaha" },
  { id: 10, title: "Keputusan Menteri Dalam Negeri" },
  { id: 11, title: "Keputusan Kepala Badan Standardisasi Nasional" },
  { id: 12, title: "Keputusan Kepala Badan Nasional Penanggulangan Bencana" },
  { id: 13, title: "Keputusan Menteri Energi dan Sumber Daya Mineral" },
  { id: 14, title: "Virtual Office" },
  { id: 15, title: "Keputusan Menteri Luar Negeri" },
  { id: 16, title: "Pembuatan PT" },
  { id: 17, title: "Keputusan Menteri Energi dan Sumber Daya Mineral" },
  { id: 18, title: "Keputusan Menteri Luar Negeri" },
  { id: 19, title: "Keputusan Menteri Kesehatan" },
  { id: 20, title: "Instruksi Presiden (INPRES)" },
  { id: 21, title: "Jasa Pembuatan PT" },
  { id: 22, title: "Keputusan Komisi Pengawas Persaingan Usaha" },
  { id: 23, title: "Pembuatan PT" },
  { id: 24, title: "Keputusan Menteri Kelautan dan Perikanan" },
];

const riskTags: RiskTagsType[] = [
  { id: 1, code: "KBLI 74902" },
  { id: 2, code: "KBLI 74902" },
  { id: 3, code: "KBLI 74902" },
  { id: 4, code: "KBLI 74902" },
  { id: 5, code: "KBLI 74902" },
  { id: 6, code: "KBLI 74902" },
  { id: 7, code: "KBLI 74902" },
];

const riskTableContents: RiskTableContentsType[] = [
  {
    id: 1,
    risk_Code: "01111",
    risk_Title: "Corn Farming",
    Description:
      "This group includes corn farming activities starting from land preparation, planting, maintenance, harvesting, and post-harvest if done as a single continuous activity. It also includes the seeding and cultivation of corn plants.",
  },
  {
    id: 2,
    risk_Code: "01112",
    risk_Title: "Wheat Farming",
    Description:
      "This group includes wheat farming activities such as land preparation, planting, maintenance, harvesting, and post-harvest when conducted as a single continuous activity for cereal wheat plants like sorghum, wheat, oats, barley, rye, millet, and similar crops. It also includes the seeding and cultivation of wheat plants.",
  },
  {
    id: 3,
    risk_Code: "01113",
    risk_Title: "Soybean Farming",
    Description:
      "This group includes soybean farming starting from land preparation, planting, maintenance, harvesting, and post-harvest when done as one continuous activity. It also includes seeding and cultivation of soybean plants.",
  },
  {
    id: 4,
    risk_Code: "01114",
    risk_Title: "Peanut Farming",
    Description:
      "This group includes peanut farming from land preparation, planting, maintenance, harvesting, and post-harvest as a continuous activity. It also includes the seeding and cultivation of peanut plants.",
  },
  {
    id: 5,
    risk_Code: "01115",
    risk_Title: "Mung Bean Farming",
    Description:
      "This group includes mung bean farming, covering land preparation, planting, maintenance, harvesting, and post-harvest activities as a single process. It also includes seeding and cultivation of mung bean plants.",
  },
  {
    id: 6,
    risk_Code: "01116",
    risk_Title: "Horticultural Beans Farming",
    Description:
      "This group includes horticultural bean farming such as string beans, kidney beans, long beans, red beans, peas, pigeon peas, and other similar crops. Activities include land preparation, planting, maintenance, harvesting, and post-harvest as a single process. It also includes seeding and cultivation.",
  },
  {
    id: 7,
    risk_Code: "01117",
    risk_Title: "Oilseed Crops Farming",
    Description:
      "This group includes farming of oilseed crops such as sesame seeds, sunflower seeds, and other similar edible oil-producing plants, including seeding and cultivation, along with all farming activities as a single process.",
  },
  {
    id: 8,
    risk_Code: "01118",
    risk_Title: "idn-edible Oilseed Crops Farming",
    Description:
      "This group includes the farming of idn-edible oil-producing seeds such as cottonrisk, flaxseed, mustard seed, niger seeds,risktor bean, and similar crops. It includes land preparation, planting, maintenance, hrisksting, post-harvest, and seeding.",
  },
  {
    id: 9,
    risk_Code: "01119",
    risk_Title: "Other Cereals, Beans, and Oilseeds Farming",
    Description:
      "This group covers farming of other cereals (excluding rice, corn, wheat), miscellaneous beans, and oil-producing seeds idt classified under groups 01111 to 01118. Includes land preparation, planting, maintenarisk harvesting, post-harvest, and seedirisk",
  },
  {
    id: 10,
    risk_Code: "02111",
    risk_Title: "Utilization of Timber in Production Forests",
    Description:
      "This group includes the utilization of timber such as planting, maintenance, harvesting, or logging of timber from production forests. Includes hardwood species like teak, pine, mahogany, rosewood, sengon, jabon, acacia, eucalyptus, sandalwood, and others.",
  },
];

const reviweCompanyLogos: CompanyLogoType[] = [
  { id: 1, link: "/images/review-company-01.png" },
  { id: 2, link: "/images/review-company-02.png" },
  { id: 3, link: "/images/review-company-03.png" },
  { id: 4, link: "/images/review-company-04.png" },
  { id: 5, link: "/images/review-company-05.png" },
  { id: 6, link: "/images/review-company-06.png" },
];

const regulationTypes: RegulationType[] = [
  { id: 1, name: "Semua type Peraturan" },
  { id: 2, name: "Instruksi Menteri Dalam Negeri" },
  { id: 3, name: "Instruksi Presiden (INPRES)" },
  { id: 4, name: "Keputusan Badan Pemeriksa Keuangan" },
  { id: 5, name: "Keputusan Kepala Badan Nasional Penanggulangan Bencana" },
  { id: 6, name: "Keputusan Kepala Badan Standardisasi Nasional" },
  { id: 7, name: "Keputusan Komisi Pengawas Persaingan Usaha" },
  { id: 8, name: "Keputusan Menteri Dalam Negeri" },
  { id: 9, name: "Keputusan Menteri Energi dan Sumber Daya Mineral" },
  { id: 10, name: "Keputusan Menteri Kelautan dan Perikanan" },
  { id: 11, name: "Keputusan Menteri Kesehatan" },
  { id: 12, name: "Keputusan Menteri Keuangan" },
  { id: 13, name: "Keputusan Menteri Luar Negeri" },
  { id: 14, name: "Keputusan Menteri Pertanian" },
  { id: 15, name: "Keputusan Presiden (KEPPRES)" },
  { id: 16, name: "Ketetapan MPR" },
  { id: 17, name: "Peraturan Arsip Nasional Republik Indonesia" },
  { id: 18, name: "Peraturan Badan Informasi Geospasial" },
  { id: 19, name: "Peraturan Badan Intelijen Negara" },
  { id: 20, name: "Peraturan Badan Keamanan Laut" },
  { id: 21, name: "Peraturan Badan Kepegawaian Negara" },
  {
    id: 22,
    name: "Peraturan Badan Kependudukan dan Keluarga Berencana Nasional",
  },
  { id: 23, name: "Peraturan Badan Koordinasi Penanaman Modal" },
  { id: 24, name: "Peraturan Badan Meteorologi, Klimatologi, dan Geofisika" },
  { id: 25, name: "Peraturan Badan Narkotika Nasional" },
  { id: 26, name: "Peraturan Badan Nasional Penanggulangan Bencana" },
  { id: 27, name: "Peraturan Badan Nasional Penanggulangan Terorisme" },
  { id: 28, name: "Peraturan Badan Pelindungan Pekerja Migran Indonesia" },
  { id: 29, name: "Peraturan Badan Pemeriksa Keuangan" },
  { id: 30, name: "Peraturan Badan Pengawas Obat dan Makanan" },
  { id: 31, name: "Peraturan Badan Pengawas Pemilihan Umum" },
  { id: 32, name: "Peraturan Badan Pengawas Tenaga Nuklir" },
  { id: 33, name: "Peraturan Badan Pengawasan Keuangan dan Pembangunan" },
  { id: 34, name: "Peraturan Badan Penyelenggara Jaminan Sosial Kesehatan" },
  { id: 35, name: "Peraturan Badan Pusat Statistik" },
  { id: 36, name: "Peraturan Badan Siber dan Sandi Negara" },
  { id: 37, name: "Peraturan Badan Standardisasi Nasional" },
  { id: 38, name: "Peraturan Badan Tenaga Nuklir Nasional" },
  { id: 39, name: "Peraturan Bank Indonesia" },
  { id: 40, name: "Peraturan Bupati (PERBUP)" },
  { id: 41, name: "Peraturan Daerah (PERDA)" },
  { id: 42, name: "Peraturan Daerah Istimewa" },
  { id: 43, name: "Peraturan Daerah Khusus Provinsi Papua (PERDASUS PAPUA)" },
  { id: 44, name: "Peraturan Dewan Perwakilan Daerah" },
  { id: 45, name: "Peraturan Dewan Perwakilan Rakyat" },
  { id: 46, name: "Peraturan Gubernur (PERGUB)" },
  { id: 47, name: "Peraturan Gubernur Lembaga Ketahanan Nasional" },
  { id: 48, name: "Peraturan Jaksa Agung" },
  { id: 49, name: "Peraturan Kejaksaan Republik Indonesia" },
  { id: 50, name: "Peraturan Kepala Arsip Nasional Republik Indonesia" },
  { id: 51, name: "Peraturan Kepala Badan Ekonomi Kreatif" },
  { id: 52, name: "Peraturan Kepala Badan Keamanan Laut" },
  { id: 53, name: "Peraturan Kepala Badan Kepegawaian Negara" },
  { id: 54, name: "Peraturan Kepala Badan Koordinasi Penanaman Modal" },
  {
    id: 55,
    name: "Peraturan Kepala Badan Meteorologi, Klimatologi, dan Geofisika",
  },
  { id: 56, name: "Peraturan Kepala Badan Narkotika Nasional" },
  { id: 57, name: "Peraturan Kepala Badan Nasional Penanggulangan Bencana" },
  { id: 58, name: "Peraturan Kepala Badan Nasional Penanggulangan Terorisme" },
  { id: 59, name: "Peraturan Kepala Badan Pengawas Obat dan Makanan" },
  {
    id: 60,
    name: "Peraturan Kepala Badan Pengawasan Keuangan dan Pembangunan",
  },
  {
    id: 61,
    name: "Peraturan Kepala Badan Pengusahaan Kawasan Perdagangan Bebas dan Pelabuhan Bebas Batam",
  },
  {
    id: 62,
    name: "Peraturan Kepala Badan Pengusahaan Kawasan Perdagangan dan Pelabuhan Bebas Sabang",
  },
  { id: 63, name: "Peraturan Kepala Badan Pusat Statistik" },
  { id: 64, name: "Peraturan Kepala Badan Standardisasi Nasional" },
  { id: 65, name: "Peraturan Kepala Badan Tenaga Nuklir Nasional" },
  { id: 66, name: "Peraturan Kepala Kepolisian Negara Republik Indonesia" },
  { id: 67, name: "Peraturan Kepala Lembaga Administrasi Negara" },
  {
    id: 68,
    name: "Peraturan Kepala Lembaga Kebijakan Pengadaan Barang/Jasa Pemerintah",
  },
  { id: 69, name: "Peraturan Kepala Perpustakaan Nasional" },
  {
    id: 70,
    name: "Peraturan Kepala Pusat Pelaporan dan Analisis Transaksi Keuangan",
  },
  { id: 71, name: "Peraturan Kepolisian Negara Republik Indonesia" },
  { id: 72, name: "Peraturan Ketua Komisi Nasional Hak Asasi Manusia" },
  { id: 73, name: "Peraturan Ketua Ombudsman Republik Indonesia" },
  { id: 74, name: "Peraturan Komisi Nasional Hak Asasi Manusia" },
  { id: 75, name: "Peraturan Komisi Pemberantasan Korupsi" },
  { id: 76, name: "Peraturan Komisi Pemilihan Umum" },
  { id: 77, name: "Peraturan Komisi Pengawas Persaingan Usaha" },
  { id: 78, name: "Peraturan Komisi Yudisial" },
  { id: 79, name: "Peraturan Lembaga Administrasi Negara" },
  { id: 80, name: "Peraturan Lembaga Ilmu Pengetahuan Indonesia" },
  {
    id: 81,
    name: "Peraturan Lembaga Kebijakan Pengadaan Barang/Jasa Pemerintah",
  },
  { id: 82, name: "Peraturan Lembaga Penjamin Simpanan" },
  { id: 83, name: "Peraturan Mahkamah Agung" },
  { id: 84, name: "Peraturan Mahkamah Konstitusi" },
  { id: 85, name: "Peraturan Majelis Permusyawaratan Rakyat" },
  { id: 86, name: "Peraturan Menteri Agama" },
  {
    id: 87,
    name: "Peraturan Menteri Agraria dan Tata Ruang/ Kepala Badan Pertanahan Nasional Republik Indonesia",
  },
  { id: 88, name: "Peraturan Menteri Badan Usaha Milik Negara" },
  { id: 89, name: "Peraturan Menteri Dalam Negeri" },
  {
    id: 90,
    name: "Peraturan Menteri Desa, Pembangunan Daerah Tertinggal, dan Transmigrasi",
  },
  { id: 91, name: "Peraturan Menteri Energi dan Sumber Daya Mineral" },
  { id: 92, name: "Peraturan Menteri Hukum dan HAM" },
  { id: 93, name: "Peraturan Menteri Kelautan dan Perikanan" },
  { id: 94, name: "Peraturan Menteri Kesehatan" },
  { id: 95, name: "Peraturan Menteri Ketenagakerjaan" },
  { id: 96, name: "Peraturan Menteri Keuangan" },
  { id: 97, name: "Peraturan Menteri Komunikasi dan Informatika" },
  {
    id: 98,
    name: "Peraturan Menteri Koordinator Bidang Kemaritiman dan Investasi",
  },
  { id: 99, name: "Peraturan Menteri Koordinator Bidang Kesejahteraan Rakyat" },
  {
    id: 100,
    name: "Peraturan Menteri Koordinator Bidang Pembangunan Manusia Dan Kebudayaan",
  },
];

const regulationRulesList: RegulationRulesListType[] = [
  {
    id: 1,
    type: "Instruksi Menteri Dalam Negeri",
    count: 10,
  },
  {
    id: 2,
    type: "Keputusan Komisi Pengawas Persaingan Usaha",
    count: 2,
  },
  {
    id: 3,
    type: "Ketetapan MPR",
    count: 2,
  },
  {
    id: 4,
    type: "Keputusan Badan Pemeriksa Keuangan",
    count: 5,
  },
  {
    id: 5,
    type: "Keputusan Menteri Keuangan",
    count: 51,
  },
  {
    id: 6,
    type: "Instruksi Presiden (INPRES)",
    count: 175,
  },
  {
    id: 7,
    type: "Keputusan Presiden (KEPPRES)",
    count: 6919,
  },
  {
    id: 8,
    type: "Keputusan Menteri Kesehatan",
    count: 27,
  },
  {
    id: 9,
    type: "Keputusan Kepala Badan Nasional Penanggulangan Bencana",
    count: 1,
  },
  {
    id: 10,
    type: "Keputusan Menteri Luar Negeri",
    count: 1,
  },
  {
    id: 11,
    type: "Keputusan Menteri Kelautan dan Perikanan",
    count: 211,
  },
  {
    id: 12,
    type: "Keputusan Kepala Badan Standardisasi Nasional",
    count: 4,
  },
  {
    id: 13,
    type: "Keputusan Menteri Energi dan Sumber Daya Mineral",
    count: 2,
  },
  {
    id: 14,
    type: "Keputusan Menteri Pertanian",
    count: 61,
  },
  {
    id: 15,
    type: "Keputusan Menteri Dalam Negeri",
    count: 24,
  },
];

const regulationTableList: RegulationTableListType[] = [
  {
    id: 1,
    type: "Peraturan Bupati (PERBUP)",
    number: 1,
    year: 2024,
    about:
      "Penentuan Kemampuan Keuangan Daerah untuk Pemberian Tunjangan Komunikasi Intensif, Tunjangan Reses dan Dana Operasional Dewan Perwakilan Rakyat Daerah year 2024",
  },
  {
    id: 2,
    type: "Peraturan Gubernur (PERGUB)",
    number: 1,
    year: 2024,
    about:
      "Alokasi dan Penggunaan Dana Bagi Hasil Cukai Hasil Tembakau Bagian Pemerintah Provinsi Jawa Tengah dan Pemerintah Kabupaten/Kota di Jawa Tengah year Anggaran 2024",
  },
  {
    id: 3,
    type: "Peraturan Pemerintah (PP)",
    number: 10,
    year: 2024,
    about:
      "Penetapan Pensiun Pokok Purnawirawan, Warakawuri/Duda, Tunjangan Anak Yatim/Piatu, Anak Yatim Piatu, dan Tunjangan Orang Tua Anggota Kepolisian Negara Republik Indonesia",
  },
  {
    id: 4,
    type: "Peraturan Bupati (PERBUP)",
    number: 1,
    year: 2024,
    about:
      "Perubahan Kelima atas Peraturan Bupati Kudus number 10 year 2022 about Pemberian Tambahan Penghasilan kepada Pegawai Aparatur Sipil Negara di Lingkungan Pemerintah Kabupaten Kudus",
  },
  {
    id: 5,
    type: "Peraturan Presiden (PERPRES)",
    number: 12,
    year: 2024,
    about: "Badan Meteorologi, Klimatologi, dan Geofisika",
  },
  {
    id: 6,
    type: "Peraturan Pemerintah (PP)",
    number: 9,
    year: 2024,
    about:
      "Penetapan Pensiun Pokok Purnawirawan, Warakawuri/Duda, Tunjangan Anak Yatim/Piatu, Anak Yatim Piatu, dan Tunjangan Orang Tua Anggota Tentara Nasional Indonesia",
  },
  {
    id: 7,
    type: "Peraturan Daerah (PERDA)",
    number: 1,
    year: 2024,
    about: "Pajak Daerah dan Retribusi Daerah",
  },
  {
    id: 8,
    type: "Peraturan Presiden (PERPRES)",
    number: 13,
    year: 2024,
    about:
      "Hak Keuangan dan Fasilitas Bagi Ketua, Wakil Ketua, dan Anggota Komisi Nasional Hak Asasi Manusia",
  },
  {
    id: 9,
    type: "Peraturan Presiden (PERPRES)",
    number: 14,
    year: 2024,
    about: "Penyelenggaraan Kegiatan Penangkapan dan Penyimpanan Karbon",
  },
];

const servicesList: ServicesListType[] = [
  { id: "svc_001", name: "PT / Perseroan Terbatas" },
  { id: "svc_002", name: "CV / Commanditaire Vennootschap" },
  { id: "svc_003", name: "PT Perorangan" },
  { id: "svc_004", name: "Penanaman Modal Asing" },
  { id: "svc_005", name: "Firma" },
  { id: "svc_006", name: "Persekutuan Perdata" },
  { id: "svc_007", name: "Perkumpulan" },
  { id: "svc_008", name: "Yayasan" },
  { id: "svc_009", name: "Virtual Office" },
  { id: "svc_010", name: "Jasa Perubahan Anggaran Dasar" },
  { id: "svc_011", name: "Jasa Pendaftaran Merek" },
  { id: "svc_012", name: "Jasa Penutupan PT" },
  { id: "svc_013", name: "Jasa NIB & OSS" },
  { id: "svc_014", name: "Jasa Pengurusan PKP" },
  { id: "svc_015", name: "Jasa Izin Restoran" },
  { id: "svc_016", name: "Jasa Izin Konstruksi" },
  { id: "svc_017", name: "Jasa Pengurusan PSE" },
  { id: "svc_018", name: "Jasa Registrasi K3L" },
  { id: "svc_019", name: "Jasa Pengurusan TDY" },
  { id: "svc_020", name: "Perjanjian Pisah Harta / Pra Nikah" },
  { id: "svc_021", name: "Jasa Pengurusan Izin KITAS" },
  { id: "svc_022", name: "Jasa Pengurusan KITAS Investor" },
  { id: "svc_023", name: "Jasa Pengurusan KITAP" },
  { id: "svc_024", name: "Jasa Pendirian UD" },
  { id: "svc_025", name: "Jasa Pengurusan SNI" },
  { id: "svc_026", name: "Jasa Pengurusan BPOM" },
  { id: "svc_027", name: "Jasa Pengurusan NPWP" },
  { id: "svc_028", name: "Jasa Pengurusan SKT" },
  { id: "svc_029", name: "Jasa Pengurusan API" },
  { id: "svc_030", name: "Jasa Pengurusan IPAK" },
  { id: "svc_031", name: "Jasa Pengurusan Sertifikat Halal" },
  { id: "svc_032", name: "Jasa Pengurusan Izin Klinik" },
  { id: "svc_033", name: "Jasa Pengurusan Sertifikasi ISO 9001" },
  { id: "svc_034", name: "Jasa Pengurusan Implementasi ISO 9001" },
  { id: "svc_035", name: "Jasa Pengurusan Sertifikasi ISO 14001" },
  { id: "svc_036", name: "Jasa Pengurusan Implementasi ISO 14001" },
  { id: "svc_037", name: "Jasa Pengurusan IMB" },
  { id: "svc_038", name: "Jasa Pengurusan NIK" },
  { id: "svc_039", name: "Jasa Pengurusan IUMK" },
  { id: "svc_040", name: "Jasa Pengurusan Paspor" },
  { id: "svc_041", name: "Jasa Pengurusan PI - Persetujuan Impor" },
  { id: "svc_042", name: "Jasa Pengurusan KITE" },
  { id: "svc_043", name: "Jasa Pengurusan IUI" },
  { id: "svc_044", name: "Jasa Pengurusan TDG" },
  { id: "svc_045", name: "Jasa Pengurusan PKRT" },
  { id: "svc_046", name: "Jasa Pengurusan PIRT" },
  { id: "svc_047", name: "Jasa Pengurusan PBF" },
  { id: "svc_048", name: "Jasa Pengurusan Izin Edar" },
  { id: "svc_049", name: "Jasa Pengurusan TDUP Mice" },
  { id: "svc_050", name: "Jasa Pengurusan SIUJPT" },
  { id: "svc_051", name: "Jasa Penutupan Perusahaan" },
  { id: "svc_052", name: "Pembuatan PT dan Virtual Office" },
];

export {
  companyLogos,
  heroServiceItems,
  mainServiceItems,
  menuItems,
  regulationRulesList,
  regulationTableList,
  regulationText,
  regulationTypes,
  reviweCompanyLogos,
  riskTableContents,
  riskTags,
  services,
  servicesList,
};
